features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
  path: ''
favicon:
  use_default: true
  path: ''
slideshow_display: 1
show_breadcrumbs: 1
slide1_head: 'Kaunis kuva'
slide2_head: 'Kiva kuva'
slide3_head: 'Kuva kolme'
slide1_desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt elit, sed do eiusmod tempor...'
slide2_desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do Lorem ipsum dolor sit amet irure dolor in reprehenderit...'
slide3_desc: 'Duis aute irure dolor in reprehenderit inLorem ipsum dolor sit amet, consectetur do Lorem ipsum dolor sit amet irure...'
slide1_url: slider1
slide2_url: slider2
slide3_url: slider3
_core:
  default_config_hash: zspC3IWx3gB7P08cyRQxXDFS-z8yLO9-4ziiOPrjkNI
slide1_image:
  - '2'
slide2_image:
  - '3'
slide3_image:
  - '4'
